var quotes = 
[
    "« La seule limite à notre développement de demain sera nos peurs d’aujourd’hui. » Franklin D.Roosevelt.",
    "« Il n'y a rien de plus profond dans l'existence humaine que l'estime de soi. » Sándor Márai.",
    "« La vie ne consiste pas à se retrouver. La vie consiste à se créer soi-même. » George Bernard Shaw.",
    "« Il vaut mieux viser la perfection et la rater que viser l'imperfection et l'atteindre »",
    "« Seuls ceux qui sont assez fous pour penser qu'ils peuvent changer le monde peuvent le faire. » Steve Jobs.",
    "« N'ayez pas peur d'être critiqué, c'est la preuve que vous devenez quelqu'un. »",
    "« Si vous voulez obtenir quelque chose que vous n'avez jamais eu, vous devez essayer quelque chose que vous n'avez jamais fait. »",
    "« La vie s'épanouit grâce au travail. »",
    "« La victoire sur soi est la plus grande victoire. »",
    "« Tomber est permis; se relever est ordonné. » Marc Aurèle",
    "« Ne vous découragez pas, c'est souvent la dernière clé du paquet qui ouvre la porte. »",
    "« Quoi que vous rêvez de faire, commencez-le. »",
    "« La meilleure façon de prédire l'avenir est de le créer. »",
    "« Soyez le changement que vous souhaitez voir dans le monde. »",
    "« Un être qui aime la vie vit d'abord pour la joie d'être vivant. » Jacques Ntéka Bokolo",
    "« Le succès est la meilleure revanche »",
    "« L'optimiste voit les problèmes et croit aux remèdes. »",
    "« Le courage n'est pas l'absence de peur, mais la capacité de surmonter ce qui vous fait peur. » Nelson Mandela",
    "« L'important n'est pas d'où vous venez, mais où vous allez. »",
    "« L'échec n'est pas le contraire du succès, il fait partie du succès »",
    "« L'ironie suprême de la vie est que personne n'en sort vivant. »",
    "« Gagner, ce n'est pas finir premier. Il ne s'agit pas de battre les autres. Il s'agit de se vaincre soi-même. »",
    "« Seuls ceux qui prennent le risque d'aller trop loin découvriront jusqu'où nous pouvons aller » Thomas Stearns Eliot",
    "« Exigez beaucoup de vous-même et attendez peu des autres. Vous éviterez ainsi bien des ennuis. »",
    "« Quand on est aimé, on ne doute de rien. Quand on aime, on doute de tout. »",
    "« La seule façon de commencer est d'arrêter de parler et de commencer à agir. »",
    "« Les étoiles ne s'aligneront jamais et les feux rouges de la vie ne deviendront jamais vertes en même temps. L'univers ne conspire pas contre vous, mais il ne fait pas non plus tout son possible pour vous faciliter les choses. Les conditions ne sont jamais parfaites. « Un jour » est une maladie qui emportera vos rêves avec vous. Les listes de « pour » et de « contre » ne sont pas meilleures. Si c'est important pour vous et que vous voulez le faire « un jour », faites-le, aujourd'hui, et corriger les choses en cours de route. » Tim Ferriss",
    "« Réussir tellement haut qu'on oublie les gens qui ne croyaient pas en nous » Yomi Denzel",
    "« Telle une étoile filante, la vie de l'Homme sur cette Terre se résume à : Naître pour être et paraître puis disparaître. » Taha-Hassine FERHAT",
    "« Dans 20 ans, vous serez plus déçu par les choses que vous n'avez pas faites que par celles que vous avez faites. Alors sortez des sentiers battus. Mettez les voiles. Explorez. Rêvez. Découvrez. » Napoléon Hill",
    "« Éviter l'échec, c'est éviter le progrès »",
    "« Aimer, c'est risquer le rejet. Vivre, c'est risquer de mourir. Espérer, c'est risquer le désespoir. Essayer, c'est risquer l'échec. Risquer est une nécessité. Seul celui qui ose risquer est vraiment libre. »",
    "« Il y a ceux qui voient les choses telles qu'elles sont et se demandent pourquoi. Moi je les vois telles qu'elles pourraient être et je me dis pourquoi pas ! » Marc Lévy",
    "« Ce n'est rien de mourir, c'est terrible de ne pas vivre. » Victor Hugo",
    "« Mieux vaut être seul qu'en mauvaise compagnie. »",
    "« Rien dans la vie n'est à craindre, tout doit être compris. Il est maintenant temps de comprendre davantage, pour avoir moins peur. » Marie Curie ",
    "« Vous ne pouvez pas fuir pour toujours ce que votre cœur désire. » Hélène Delanoy",
    "« Souvenez-vous uniquement des beaux souvenirs du passé. Vivez votre présent en harmonie avec votre cœur. Et attendez que l'avenir vienne à vous avec sagesse. » Valérie Coeur",
    "« Le passé est ce qui n'existe plus. Vivre dans le passé, ce n'est pas vivre : c'est être mort ou peut-être vouloir mourir... »",
    "« Les hommes ne cesseront jamais d'avoir des rêves. » Marshall D. Teach, One Piece",
    "« La beauté du résultat se retrouve dans les efforts que vous avez déployés pour les obtenir. » Dali Dutilleul",
    "« Si tu es né pauvre, ce n'est pas de ta faute, mais si tu meurs pauvre, c'est de ta faute. »",
    "« À 4 ans, je savais déjà que j'allais devenir le boss. » Eiichiro Oda",
    "« N'essayez pas d'être bon, essayez de devenir le meilleur. » MrDreamax",
    "« Travaillez comme si votre vie en dépendait. Pour quoi ? Parce que c'est le cas. » MrDreamax",
    "« Travaillez dur ET intelligemment. »",
    "« Quand tu te divertis, ce n'est pas toi qui tues le temps, mais c'est le temps qui te tue. »",
    "« Premièrement, changez votre vie, puis deuxièmement, changez le monde. » MrDreamax",
    "« Quand vous comprenez que stagner est la même chose que mourir, alors vous avez tout compris. Si vous restez immobile, le monde avance, donc vous reculez. N'attendez pas, changez maintenant. » MrDreamax",
    "« La beauté est dans les yeux du spectateur. » Oscar Wilde",
    "« Faites de votre vie un rêve et d'un rêve une réalité. » Antoine de Saint-Exupéry",
    "« Vivez comme si vous deviez mourir demain. Apprenez comme si vous deviez vivre éternellement. » Gandhi",
    "« Ce qui compte chez un homme, ce n'est pas la couleur de sa peau ou la texture de ses cheveux, mais la texture et la qualité de son âme. » Martin Luther King",
    "« Deux choses sont infinies : l'Univers et la bêtise humaine. Mais en ce qui concerne l'Univers, je n'en ai pas encore acquis la certitude absolue. » Albert Einstein",
    "« C'est de l'enfer des pauvres qu'est fait le paradis des riches. » Victor Hugo",
    "« Il n'y a rien de pire que ceux qui ne veulent pas entendre. » Molière",
    "« C'est à vous de décider ce en quoi vous voulez croire. » Edward D. Newgate, One Piece",
    "« Le mal n'engendre que le mal, et la destruction ne fait naitre que la haine. Au final nous sommes tous des êtres humains, aimons-nous les uns les autres. » Brook, One Piece",
    "« Le fait de ne jamais douter, c'est ça qui fait la force. » Rayleigh, One Piece",
    "« Etre différent c'est ce qu'il y a de plus beau dans la vie, je prends ça comme un compliment. C'est ce qui me rend unique ! » Brook, One Piece",
    "« Comment l'humanité peut-elle s'épanouir alors qu'elle fait couler son propre sang ? » Dragon, One Piece",
    "« Dans la vie il n'est pas interdit de pleurer, mais cela ne doit en aucun cas t'empecher d'avancer. » Shanks, One Piece",
    "« Ne pense pas simplement à tout ce que tu as perdu, le passé appartient au passé. Essaie de te concentrer sur ce qu'il te reste, c'est ça le plus important. » Jimbei, One Piece",
    "« Quand croyez-vous qu'un homme meurt ? Lorsqu'il se prend une balle en plein coeur ? Lorsqu'il contracte une maladie incurable ? Lorsqu'il avale une soupe de champignons vénéneux ? Non. Il meurt, dès qu'on ne se souvient plus de lui. » Dr Hiluluk, One Piece",
    "« C'est pas une question de possibilité, c'est juste une question de volonté. » Monkey D. Luffy",
    "« Les choses ne se déroulent pas toujours comme on le voudrait. » Madara, Naruto",
    "« Les minutes sont plus puissantes que des balles. Ne perdez pas votre temps. » Eliott Exe",
]

var randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
document.getElementById("random_quote").innerHTML = randomQuote;
